//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTtool.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Account1 = new HashSet<Account>();
            this.Account11 = new HashSet<Account>();
            this.Expenditure = new HashSet<Expenditure>();
            this.Expenditure1 = new HashSet<Expenditure>();
            this.Expenditure2 = new HashSet<Expenditure>();
            this.ExpenditureShare = new HashSet<ExpenditureShare>();
        }
    
        public short Id { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string AccountGroupId { get; set; }
        public string Name { get; set; }
        public short Creator { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<short> Editor { get; set; }
        public Nullable<System.DateTime> EditDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account11 { get; set; }
        public virtual Account Account3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure> Expenditure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure> Expenditure1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expenditure> Expenditure2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenditureShare> ExpenditureShare { get; set; }
        public virtual AccountGroup AccountGroup { get; set; }
    }
}
