//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JTtool.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expenditure()
        {
            this.ExpenditureShare = new HashSet<ExpenditureShare>();
        }
    
        public int Id { get; set; }
        public short Payer { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public string Item { get; set; }
        public int Price { get; set; }
        public bool IsInstallment { get; set; }
        public byte Periods { get; set; }
        public bool IsAlways { get; set; }
        public short Creator { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<short> Editor { get; set; }
        public Nullable<System.DateTime> EditDatetime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenditureShare> ExpenditureShare { get; set; }
    }
}
